
const diccionario = {
    Collserola: ['Comenzamos esta lista con los mejores parques naturales cerca de Barcelona para hablarte del Parque natural de la sierra de Collserola que se trata del espacio natural más próximo a la ciudad condal De hecho, desde la misma ciudad podrás divisar esta zona natural que está al norte y que se distingue muy fácilmente porque hay instalada una vistosa torre de comunicaciones y, también, por el templo que hay en el Tibidabo.', 'Comencem aquesta llista amb els millors parcs naturals a prop de Barcelona per parlar del Parc natural de la serra de Collserola que es tracta de l´espai natural més proper a la ciutat comtal. De fet, des de la mateixa ciutat podràs albirar aquesta zona natural que està al nord i que es distingeix molt fàcilment perquè hi ha instal·lada una vistosa torre de comunicacions i, també, pel temple que hi ha al Tibidabo.'],
    Collserola2: ['El Parc de Collserola se trata de un espacio natural que cuenta con 8000 hectáreas de flora y naturaleza. Aquí encontrarás especies como encinas, robles, pinos, etcétera. Es una visita interesante porque, además de zonas naturales, también te irás encontrando con ermitas e iglesias antiguas que le dan un aire auténtico a tu visita.', 'El Parc de Collserola és un espai natural que compta amb 8000 hectàrees de flora i natura. Aquí trobaràs espècies com alzines, roures, pins, etcètera. És una visita interessant perquè, a més de zones naturals, també t´aniràs trobant amb ermites i esglésies antigues que donen un aire autèntic a la teva visita.'],
    Collserola3: ['Y, por supuesto, uno de los espacios más visitados de Collserola por todas las familias es el parque de Tibidabo, un parque de atracciones que cuenta con unas imponentes vistas de la ciudad condal. Por este motivo, es uno de los destinos favoritos entre familias que quieren hacer excursiones cerca de Barcelona, ¡tienes que visitarlo!', ' I, per descomptat, un dels espais més visitats de Collserola per totes les famílies és el parc de Tibidabo, un parc d´atraccions que compta amb unes vistes imponents de la ciutat comtal. Per aquest motiu, és una de les destinacions preferides entre famílies que volen fer excursions a prop de Barcelona, ​​has de visitar-lo! '],
    Home: ['¿Te gusta la naturaleza? Debes saber que, aunque vivas en Barcelona o en su área metropolitana, cerca de la ciudad encontrarás espacios naturales que son perfectos para perderse y disfrutar de un día al aire libre. En este listado de Salir.com hemos recopilado los mejores parques naturales cerca de Barcelona y el más lejano de todos está a menos de 1 hora y media, por tanto, podrás hacer una escapada de un día tranquilamente. Todos estos espacios son ideales para descubrir junto a tus amigos o familia y te ofrecen bellos rincones donde la naturaleza muestra su mejor faceta. ¡Descúbrelos!' , ' T´agrada la natura? Has de saber que, encara que visquis a Barcelona oa la seva àrea metropolitana, a prop de la ciutat trobaràs espais naturals que són perfectes per perdre´s i gaudir d´un dia a l´aire lliure. En aquest llistat de Salir.com hem recopilat els millors parcs naturals a prop de Barcelona i el més llunyà de tots és a menys d´1 hora i mitja, per tant podràs fer una escapada d´un dia tranquil·lament. Tots aquests espais són ideals per descobrir al costat dels teus amics o família i t´ofereixen bells racons on la natura mostra la millor faceta. Descobreix-los! '],
    Valld: ['Uno de los parques naturales de Barcelona ciudad y que merece la pena conocer es el Pantano de Vallvidrera, un embalse hidráulico que está situado en el barrio que le da nombre (Vallvidrera) y donde podrás encontrar un espacio natural perfecto para ir con tu familia o con amigos.' , ' Un dels parcs naturals de Barcelona ciutat i que val la pena conèixer és el Pantà de Vallvidrera, un embassament hidràulic que està situat al barri que li dóna nom (Vallvidrera) i on podràs trobar un espai natural perfecte per anar amb la teva família o amb amics. '],
    Valld2: ['Actualmente, este rincón es un oasis en la ciudad condal, ya que está rodeado de árboles y naturaleza que invita a la desconexión. El nivel del agua se mantiene en cotas altas gracias a la existencia de fuentes permanentes. Es un sitio perfecto para ir con perros en Barcelona y disfrutar de un picnic, así como una sesión refrescante para el verano.' , ' Actualment, aquest racó és un oasi a la ciutat comtal, ja que està envoltat d´arbres i natura que convida a la desconnexió. El nivell de l´aigua es manté a cotes altes gràcies a l´existència de fonts permanents. És un lloc perfecte per anar amb gossos a Barcelona i gaudir d´un pícnic, així com una sessió refrescant per a l´estiu.']
}

export default diccionario;